name = "BiliStalkerMCP"
version = "2.3"
description = "A Model Context Protocol (MCP) server for comprehensive Bilibili user data acquisition."
license = "MIT"
repository = "https://github.com/222wcnm/BiliStalkerMCP"

[mcp_server]
type = "process"
command = ["uvx", "bili-stalker-mcp"]
# Smithery will automatically set the PORT environment variable.
# Ensure your server listens on the port specified by this environment variable.
# You may need to modify your server.py to read the PORT from os.environ.

[deployment]
# This section is for Smithery's cloud deployment.
# You can specify regions and other settings here.
# For now, we'll leave it minimal.
regions = ["us-east-1"] 

# It's good practice to define the environment variables your server needs.
# The actual values should be set securely in the Smithery UI or via their CLI, not here.
[environment]
variables = [
    { name = "SESSDATA", description = "Your Bilibili SESSDATA cookie.", secret = true },
    { name = "BILI_JCT", description = "Your Bilibili BILI_JCT cookie.", secret = true },
    { name = "BUVID3", description = "Your Bilibili BUVID3 cookie.", secret = true }
]
